yousearch_py_api/yousearch_py_api/urls.py
from django.urls import path, include

urlpatterns = [
    path('yt/', include('youtube.urls')),
]

yousearch_py_api/youtube/urls.py
from django.conf.urls import url

from . import views

app_name = 'youtube'
urlpatterns = [
	url(r'^searchApi/$', views.search_vid, name='search_api'),
	url(r'^home/$', views.index, name='home'),
	url(r'^search/$', views.search, name='search'),
]

yousearch_py_api/youtube/views.py
import math
import traceback

from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.status import HTTP_500_INTERNAL_SERVER_ERROR, HTTP_200_OK

from youtube import constants
from youtube.search import fetch_search_results


@api_view(['GET'])
def search_vid(request):
    """ Search video details using API """
    try:
        text = request.GET.get(constants.SEARCH_QUERY, '')
        res_count = int(request.GET.get(constants.PAGE, 1))
        title_search = request.GET.get(constants.TITLE_QUERY, None)
        desc_search = request.GET.get(constants.DESCRIPTION_QUERY, None)
        results = fetch_search_results(text, int(res_count) * 10, title_search, desc_search)
        return Response(results, status=HTTP_200_OK)
    except Exception as e:
        traceback.print_exc()
        return Response(status=HTTP_500_INTERNAL_SERVER_ERROR)

@api_view(['GET'])
def index(request):
    """ Render Home page template """
    try:
        results = fetch_search_results()
        return render(request, 'index.html', results)
    except Exception as e:
        traceback.print_exc()

@api_view(['GET', 'POST'])
def search(request):
    """ Search API to render the template """
    if request.method == 'GET':
        max_res = int(request.GET.get(constants.MAX, 0))
        order = request.GET.get(constants.ORDER, 0)
        order = int(order) if order else 0
        text = request.GET.get(constants.SEARCH_QUERY, '')
        res_count = int(request.GET.get(constants.PAGE, 1))

        if res_count < 1:
            res_count = 1
        elif res_count > math.ceil(max_res / 10):
            res_count = math.ceil(max_res / 10)

        title_search = request.GET.get(constants.TITLE_QUERY, None)
        desc_search = request.GET.get(constants.DESCRIPTION_QUERY, None)
    else:
        order = int(request.POST.get(constants.ORDER, 0))
        text = request.POST.get(constants.SEARCH_QUERY, '')
        res_count = int(request.POST.get(constants.PAGE, 1))
        title_search = request.POST.get(constants.TITLE_QUERY, None)
        desc_search = request.POST.get(constants.DESCRIPTION_QUERY, None)

    results = fetch_search_results(text, int(res_count) * 10, title_search, desc_search, order=order)
    return render(request, 'index.html', results)

yousearch_py_api/youtube/templates/index.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{%  static  'css/styles.css'  %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{%  static  'images/brand.png'  %}">
    <title>Search Youtube videos!</title>
  </head>
  <body class="bg-dark">
    {% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{%  static  'images/brand.png'  %}" alt="" width="25" height="24" class="d-inline-block align-text-top">&nbsp;YouSearch</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" onClick="refreshPage()" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'youtube:home' %}">Reload</a>
              </li>
            </ul>
            <form class="collapse navbar-collapse" action="{% url 'youtube:search' %}" method="post">
              {% csrf_token %}
              <input class="form-control me-2" type="search" name="q" placeholder="Search YouTube Here" aria-label="Search">
              <button class="btn bg-light btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
<!--    <div class="container-fluid bg-light">-->


<!--    </div>-->
      <div class="container-fluid add-large-margin-top">
          <div class="row">
            <div class="col-sm text-center">
              <button type="button" class="btn btn-primary btn-sm" onclick="location.href='{% url 'youtube:search'%}?order={{ order|add:1 }}&page={{page}}&max={{ total_results }}&q={{q}}'">Sort by date</button>
            </div>
            <div class="col-sm text-center">

            </div>
            <div class="col-sm text-center">
              <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='{% url 'youtube:search'%}?order={{ order }}&page={{page|add:'-1'}}&max={{ total_results }}&q={{q}}'">Previous</button>
              <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='{% url 'youtube:search'%}?order={{ order }}&page={{page|add:1}}&max={{ total_results }}&q={{q}}'">Next</button>
            </div>
          </div>
      </div>
      <div class="container-fluid add-large-margin-top">
        <div class="row">
          <div class="col-sm text-center text-light"></div>
          <div class="col-sm text-center text-light">
            Showing {{page_start}} - {{ page_end }} of {{ total_results }} results
          </div>
          <div class="col-sm text-center text-light"></div>
        </div>
      </div>
      <div class="container-fluid add-large-margin-top">
        <div class="row">
          <div class="col-sm "></div>
          <div class="col-sm bg-dark set-md-width">
            <!--This is the div of items-->
            {% for item in results %}
              <div class="container item-div">
                  <div class="row">
                      <div class="col img center">
                          <img src="{{ item.thumbnail }}" class="rounded float-start default-thumbnail-size" alt="This is text of the video">
                      </div>
                      <div class="col-9 text-light">
                        <a href="{{ item.videoLink }}" target="_blank" class="text-title">{{ item.trimmedTitle }}</a>
                        <p class="text-subtitle">{{ item.channelTitle }}</p>
                        <p class="text-description">{{ item.publishTime }}</p>
                        <p class="text-description">{{ item.description }}</p>
                      </div>
                    </div>
              </div>
            {% endfor %}
          </div>
          <div class="col-sm text-center"></div>
        </div>
      </div>
    {% endblock %}
    <script>
    function refreshPage(){
        window.location.reload();
    }
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>